import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const myFont = localFont({
  src: "../public/fonts/Comic Sans MS.ttf",
  display: "swap", // Verhindert das Blinken von Standard-Schriften
  variable: "--font-rooster",
});

export default function RootLayout({ children }) {
  return (
    <html lang="de" className={myFont.variable}>
      <body>{children}</body>
    </html>
  );
}


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
